import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Snapchat",
  description: "Generated by create next app",
  icons: {
    icon: '/snapchat-logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Set favicon, title & description for all page */}
      <Head>
        <link rel="icon" href="/snapchat-logo.png" />
        <title>{metadata.title as string}</title>
        <meta name="description" content={metadata.description as string} />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
